name: grab_go_admin
description: "GrabGo Admin - Administrative dashboard for GrabGo food delivery platform."
publish_to: 'none'
version: 1.0.0+1
resolution: workspace

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  grab_go_shared:
    path: ../grab_go_shared
  google_fonts: ^6.2.1
  provider: ^6.1.1
  flutter_svg: ^2.0.10+1
  fl_chart: ^1.1.1
  chopper: ^8.4.0
  http: ^1.1.2
  json_annotation: ^4.9.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_gen_runner: ^5.5.0
  build_runner: ^2.4.9
  chopper_generator: ^8.4.0
  json_serializable: ^6.9.0

flutter:
  uses-material-design: true
